first step to a simple InitializedOperator
geo-engine/geoengine pull request #172
Opened 2021-03-01 09:10 UTC by jdroenner

remove params from InitializedOperatorImpl

2021-03-01 09:11 UTC, jdroenner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor InitializedOperatorImpl](https://trello.com/c/ZgQvJKhw/177-refactor-initializedoperatorimpl)

2021-03-01 13:13 UTC, ChristianBeilschmidt commented
I guess that is an improvement :+1:. However, the task states that we tried to move from *Lambda function to builder pattern*. This is not in this PR, yet.

2021-03-01 13:13 UTC, ChristianBeilschmidt requested changes

2021-03-01 13:13 UTC, ChristianBeilschmidt commented on operators/src/processing/point_in_polygon.rs
> +pub type InitializedPointInPolygonFilter = InitializedOperatorImpl<VectorResultDescriptor, ()>;
I guess we should use the moment to introduce an empty dummy struct here as state.

2021-03-02 08:15 UTC, jdroenner commented
i know but i had to start somewhere.

2021-03-02 11:08 UTC, jdroenner commented
will add builder later

2021-03-02 15:16 UTC, ChristianBeilschmidt approved these changes

2021-03-02 15:17 UTC, merged