ogr_time
geo-engine/geoengine pull request #217
Opened 2021-04-28 14:53 UTC by michaelmattig

2021-04-28 14:53 UTC, michaelmattig commented
![](https://github.trello.services/images/mini-trello-icon.png) [Daten jeweils mit OGR-Quelle laden](https://trello.com/c/HKcsvtu3/128-daten-jeweils-mit-ogr-quelle-laden)

2021-04-29 12:43 UTC, ChristianBeilschmidt requested changes

2021-04-29 15:22 UTC, michaelmattig commented on operators/src/source/ogr_source.rs
> +    Auto,
`Auto` is for everything Gdal can parse which also includes Iso but also many other formats. I see no need to parse Iso ourselfs. So my idea was to use Auto if Gdal can parse it and custom if we parse it ourselfs.

2021-04-29 15:45 UTC, michaelmattig commented on operators/src/source/ogr_source.rs
> +                // TODO: support date without time as well?
17bf927e34a21377ecf24eabffecf2158f7a44ee

2021-04-29 15:45 UTC, michaelmattig commented on services/Cargo.toml
> +gdal = { version = "0.7", features = ["datetime"] }
we are on it, but the CI makes problems. No idea what to do there: https://github.com/geo-engine/geoengine/pull/215

2021-04-29 15:46 UTC, michaelmattig commented on operators/src/source/ogr_source.rs
> +                    .into_string()
17bf927e34a21377ecf24eabffecf2158f7a44ee

2021-04-29 15:47 UTC, michaelmattig commented on operators/test-data/vector/data/points_with_iso_time.json
> +        "time_end": "2014-06-01T00:00:00Z"
this was just an inconsistency in the test data. they weren't actually all iso and now they are.

2021-04-29 15:51 UTC, michaelmattig commented on services/src/handlers/datasets.rs
>          "start",
ec80627aa13d252b5cfdd20dfa541a50a3a10ae4

2021-04-29 15:51 UTC, michaelmattig commented on services/src/handlers/datasets.rs
>          "end",
ec80627aa13d252b5cfdd20dfa541a50a3a10ae4

2021-04-30 09:15 UTC, merged