Contributing section in README.md
geo-engine/geoengine pull request #268
Opened 2021-06-15 07:47 UTC by ChristianBeilschmidt

2021-06-15 07:47 UTC, ChristianBeilschmidt commented
![](https://github.trello.services/images/mini-trello-icon.png) [Auf CLA in github readme hinweisen](https://trello.com/c/YXR6Zufe/603-auf-cla-in-github-readme-hinweisen)

2021-06-18 16:00 UTC, michaelmattig requested changes
.

2021-06-18 16:00 UTC, michaelmattig commented on CONTRIBUTING.md
> +Congratulations! The Geo Engine team thanks you for your contribution. ✨
maybe 
```suggestion
Congratulations! The Geo Engine community thanks you for your contribution. ✨
```

2021-06-21 07:44 UTC, ChristianBeilschmidt commented on CONTRIBUTING.md
> +Congratulations! The Geo Engine team thanks you for your contribution. ✨
d82a873

2021-06-21 07:44 UTC, ChristianBeilschmidt commented on CONTRIBUTING.md
> +You can either rebuttal a comment or provide a fix.
d82a873

2021-06-21 07:44 UTC, ChristianBeilschmidt commented on CONTRIBUTING.md
> +The core team usually makes a code review on each pull request.
d82a873

2021-06-21 07:44 UTC, ChristianBeilschmidt commented on CONTRIBUTING.md
> +In case you have difficulties using Geo Engine, feel free to ask for help!
d82a873

2021-06-21 07:44 UTC, ChristianBeilschmidt commented on CONTRIBUTING.md
> +If you want to discuss new features before implementing them, feel free to start a discussion and get feedback on your idea.
d82a873

2021-06-21 13:53 UTC, michaelmattig commented on CONTRIBUTING.md
> +In case you have difficulties using Geo Engine, feel free to ask for help!
I would leave support@ for paying(?) customer/users. How about contribute@ or dev@ or maybe just simply info@ ?

2021-06-21 14:11 UTC, ChristianBeilschmidt commented on CONTRIBUTING.md
> +In case you have difficulties using Geo Engine, feel free to ask for help!
f129362

2021-06-21 14:13 UTC, ChristianBeilschmidt commented on CONTRIBUTING.md
> +In case you have difficulties using Geo Engine, feel free to ask for help!
d7c276c

2021-06-21 14:28 UTC, merged