inner_aggregation
geo-engine/geoengine pull request #287
Opened 2021-07-08 12:22 UTC by michaelmattig

2021-07-08 12:22 UTC, michaelmattig commented
![](https://github.trello.services/images/mini-trello-icon.png) [Innere Aggregation bei Raster-Vektor-Join](https://trello.com/c/iqYOGYuJ/92-innere-aggregation-bei-raster-vektor-join)

2021-07-11 15:50 UTC, jdroenner requested changes
lets talk about this

2021-07-11 15:50 UTC, jdroenner commented on operators/src/processing/raster_vector_join/mod.rs
> +    /// Specifies which method is used for aggregating values for a feature
for each feature?

So this is the aggregation which is used to generate a single value for each feature? E.g. all pixels inside of a polygon?

2021-07-11 15:50 UTC, jdroenner commented on operators/src/processing/raster_vector_join/mod.rs
> +    pub temporal_aggregation: TemporalAggregationMethod,
and this is the aggregation over time?

2021-07-11 15:50 UTC, jdroenner commented on operators/src/processing/raster_vector_join/mod.rs
> +/// points inside a `MultiPoint` feature. Choosing None leads to an
i think we have to separate multi-features and things like polygons where each single feature can contain multiple pixels.
for points we will hit  only one pixel, however, lines and polygons can hit multiple pixels.

2021-07-11 15:50 UTC, jdroenner commented on operators/src/processing/raster_vector_join/aggregator.rs
>  impl TypedAggregator {
impl Aggregator for TypedAggregator will make things easier i think

2021-07-11 15:50 UTC, jdroenner commented on operators/src/processing/raster_vector_join/aggregator.rs
> +    null: bool,
is_null?

2021-07-11 15:50 UTC, jdroenner commented on operators/src/processing/raster_vector_join/per_feature_aggregator.rs
> +impl TypedPerFeatureAggregator {
impl PerFeatureAggregator for TypedPerFeatureAggregator

2021-07-22 15:58 UTC, closed without merging