Projection coordinate lookup
geo-engine/geoengine pull request #348
Opened 2021-09-16 14:08 UTC by jdroenner

2021-09-16 14:09 UTC, jdroenner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Koordinaten in der Projektion erst checken, dann umprojezieren.](https://trello.com/c/UzBihqEA/394-koordinaten-in-der-projektion-erst-checken-dann-umprojezieren)

2021-09-17 14:03 UTC, michaelmattig requested changes

2021-09-17 14:03 UTC, michaelmattig commented on operators/src/adapters/raster_subquery_adapter.rs
>          let projected_coords = project_coordinates_fail_tolerant(&coords, &proj);
does it still have to be fail tolerant?

2021-09-20 16:01 UTC, jdroenner commented on operators/src/adapters/raster_subquery_adapter.rs
> +        let valid_bounds_proj =
d5f3319

2021-09-20 16:01 UTC, jdroenner commented on operators/src/adapters/raster_subquery_adapter.rs
> +        let valid_bounds = self
d5f3319

2021-09-20 16:01 UTC, jdroenner commented on operators/src/adapters/raster_subquery_adapter.rs
>          let projected_coords = project_coordinates_fail_tolerant(&coords, &proj);
d5f3319

2021-09-20 16:02 UTC, jdroenner commented
redesigned the bounds check and generate valid bounds only once

2021-09-21 08:22 UTC, michaelmattig approved these changes

2021-09-21 08:23 UTC, merged