Ogr-source-scheduling
geo-engine/geoengine pull request #434
Opened 2022-01-04 13:45 UTC by ChristianBeilschmidt

2022-01-04 14:28 UTC, ChristianBeilschmidt commented
![](https://github.trello.services/images/mini-trello-icon.png) [OGR-Source: Nur für einen Poll blockieren](https://trello.com/c/v1fDsAFg/505-ogr-source-nur-f%C3%BCr-einen-poll-blockieren)

2022-01-06 15:36 UTC, jdroenner approved these changes

2022-01-06 15:36 UTC, jdroenner requested changes

2022-01-06 15:36 UTC, jdroenner commented on datatypes/Cargo.toml
> +gdal = { version = "0.11", features = ["bindgen"] }
please remove the bindgen feature

2022-01-06 15:36 UTC, jdroenner commented on operators/Cargo.toml
> +gdal = { version = "0.11", features = ["bindgen"] }
please remove the bindgen feature

2022-01-06 15:40 UTC, ChristianBeilschmidt commented on operators/Cargo.toml
> +gdal = { version = "0.11", features = ["bindgen"] }
23018a9

2022-01-06 15:40 UTC, ChristianBeilschmidt commented on datatypes/Cargo.toml
> +gdal = { version = "0.11", features = ["bindgen"] }
23018a9

2022-01-06 16:06 UTC, jdroenner approved these changes

2022-01-06 16:07 UTC, jdroenner commented
bors merge

2022-01-06 17:07 UTC, merged