Big_tiff
geo-engine/geoengine pull request #473
Opened 2022-02-15 09:18 UTC by jdroenner

2022-02-15 09:19 UTC, jdroenner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Immer BigTiff verwenden](https://trello.com/c/pPfS5dXI/603-immer-bigtiff-verwenden)

2022-02-15 18:15 UTC, ChristianBeilschmidt requested changes
Maybe indicate the threshold and heuristic more with variable names. Nothing else to complain. Should try it out after it is merged.

2022-02-15 18:15 UTC, ChristianBeilschmidt commented on operators/src/util/raster_stream_to_geotiff.rs
> +const BIG_TIFF_BYTES: usize = 2_000_000_000; // ~ 2GB + 2GB for overviews + buffer for headers
```suggestion
const BIG_TIFF_BYTE_THRESHOLD: usize = 2_000_000_000; // ~ 2GB + 2GB for overviews + buffer for headers
```

2022-02-15 18:15 UTC, ChristianBeilschmidt commented on operators/src/util/raster_stream_to_geotiff.rs
> +        let byte_size = width as usize * height as usize * std::mem::size_of::<P>();
```suggestion
        let uncompressed_byte_size = width as usize * height as usize * std::mem::size_of::<P>();
```

2022-02-15 20:37 UTC, jdroenner commented on operators/src/util/raster_stream_to_geotiff.rs
> +        let byte_size = width as usize * height as usize * std::mem::size_of::<P>();
[55358bb](https://github.com/geo-engine/geoengine/pull/473/commits/55358bb33360ff88ff9e5716dd67069ed3053ca3)

2022-02-15 20:37 UTC, jdroenner commented on operators/src/util/raster_stream_to_geotiff.rs
> +const BIG_TIFF_BYTES: usize = 2_000_000_000; // ~ 2GB + 2GB for overviews + buffer for headers
[55358bb](https://github.com/geo-engine/geoengine/pull/473/commits/55358bb33360ff88ff9e5716dd67069ed3053ca3)

2022-02-16 05:40 UTC, ChristianBeilschmidt approved these changes

2022-02-16 05:41 UTC, ChristianBeilschmidt commented
bors merge

2022-02-16 18:16 UTC, merged