skip layer providers instead of failing
geo-engine/geoengine pull request #595
Opened 2022-08-18 08:07 UTC by michaelmattig

2022-08-18 08:07 UTC, michaelmattig commented
![](https://github.trello.services/images/mini-trello-icon.png) [TonicTransport Error beim Auflisten des GfbioDataProviders](https://trello.com/c/pCIKLFAy/951-tonictransport-error-beim-auflisten-des-gfbiodataproviders)

2022-08-18 14:28 UTC, ChristianBeilschmidt requested changes

2022-08-18 14:28 UTC, ChristianBeilschmidt commented on services/src/handlers/layers.rs
> +                        collection_id: provider.root_collection_id().await?,
Shouldn't we also not just skip when this error occurs here?

2022-08-22 15:07 UTC, ChristianBeilschmidt approved these changes

2022-08-22 15:07 UTC, ChristianBeilschmidt commented
bors merge

2022-08-22 16:07 UTC, merged