split coverage and ci. Add tarpaulin args
geo-engine/geoengine pull request #622
Opened 2022-09-12 13:43 UTC by jdroenner

2022-09-12 15:08 UTC, jdroenner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Split CI and Coverage. Fix Coverage.](https://trello.com/c/SCGtk1a3/989-split-ci-and-coverage-fix-coverage)

2022-09-12 15:12 UTC, ChristianBeilschmidt approved these changes

2022-09-12 15:13 UTC, ChristianBeilschmidt commented
bors merge

2022-09-12 16:25 UTC, ChristianBeilschmidt commented
Can you increase the timeout for bors?
https://forum.bors.tech/t/bors-keeps-timing-out/87

2022-09-12 19:05 UTC, ChristianBeilschmidt submitted a review, later dismissed

2022-09-12 19:05 UTC, ChristianBeilschmidt commented
bors merge

2022-09-13 10:30 UTC, ChristianBeilschmidt commented
bors merge

2022-09-13 10:30 UTC, ChristianBeilschmidt approved these changes

2022-09-13 10:31 UTC, ChristianBeilschmidt commented
bors merge

2022-09-13 13:01 UTC, ChristianBeilschmidt requested changes
You need to change the https://github.com/geo-engine/geoengine/blob/master/bors.toml to reflect the new name of the coverage task.
I think it is now `coveralls` instead of `coverage`.
This is why we cannot merge it.

2022-09-13 13:01 UTC, ChristianBeilschmidt commented on bors.toml
> +timeout-sec = 14400
4 hours is quite long, what about 2 hours?

2022-09-14 10:20 UTC, ChristianBeilschmidt approved these changes

2022-09-14 10:21 UTC, ChristianBeilschmidt commented
bors merge

2022-09-14 11:21 UTC, merged