new methods for temporal raster aggregator
geo-engine/geoengine pull request #689
Opened 2022-11-30 17:43 UTC by ChristianBeilschmidt

- [ ] I added an entry to [`CHANGELOG.md`](CHANGELOG.md) if knowledge of this change could be valuable to users.

---

Here is a brief summary of what I did:

<TEXT>

2022-11-30 17:44 UTC, ChristianBeilschmidt commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rasteraggregation: Count + Summe](https://trello.com/c/N6BMAeN4/821-rasteraggregation-count-summe)

2022-12-06 12:43 UTC, jdroenner requested changes

2022-12-06 13:20 UTC, ChristianBeilschmidt commented on operators/src/processing/temporal_raster_aggregation/subquery.rs
> +                // TODO: handle case where this could stays empty
[ceee342](https://github.com/geo-engine/geoengine/pull/689/commits/ceee3420733edd171b699a198456b1f21674d8a7)

Actually, I don't know. This is just the current implementation, I just copied it.

2022-12-06 18:19 UTC, jdroenner commented
bors merge

2022-12-06 20:31 UTC, jdroenner commented
bors retry

2022-12-06 20:34 UTC, jdroenner commented
bors merge

2022-12-06 21:16 UTC, merged