Layers to workflow
geo-engine/geoengine pull request #692
Opened 2022-12-05 18:15 UTC by jdroenner

- [ ] I added an entry to [`CHANGELOG.md`](CHANGELOG.md) if knowledge of this change could be valuable to users.

---

Here is a brief summary of what I did:

<TEXT>

2022-12-05 19:52 UTC, jdroenner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Layer zeigen eine Information über ihre Gültigkeit.](https://trello.com/c/IYjLw7qr/1026-layer-zeigen-eine-information-%C3%BCber-ihre-g%C3%BCltigkeit)

2022-12-06 13:17 UTC, ChristianBeilschmidt requested changes

2022-12-06 18:17 UTC, jdroenner commented on services/src/handlers/layers.rs
> +) -> Result<impl Responder> {
[d42dbb6](https://github.com/geo-engine/geoengine/pull/692/commits/d42dbb6cb0508ea353f4dcaa40d9ec91acda2ad3)

2022-12-09 10:11 UTC, ChristianBeilschmidt commented
Please resolve the conflicts.

2022-12-12 09:32 UTC, ChristianBeilschmidt approved these changes

2022-12-12 09:32 UTC, ChristianBeilschmidt commented
bors merge

2022-12-12 11:21 UTC, ChristianBeilschmidt commented
bors merge

2022-12-12 11:21 UTC, ChristianBeilschmidt commented
bors retry

2022-12-12 12:35 UTC, ChristianBeilschmidt commented
bors merge

2022-12-12 19:04 UTC, jdroenner commented
bors retry

2022-12-12 19:49 UTC, merged