Pie-chart
geo-engine/geoengine pull request #694
Opened 2022-12-09 15:14 UTC by ChristianBeilschmidt

- [ ] I added an entry to [`CHANGELOG.md`](CHANGELOG.md) if knowledge of this change could be valuable to users.

---

Here is a brief summary of what I did:

<TEXT>

2022-12-12 17:37 UTC, jdroenner requested changes

2022-12-12 17:37 UTC, jdroenner commented on datatypes/src/plots/pie_chart.rs
> +                details: "All pies of the pie chart must have a positive value".to_string()
Should that be "slices"? Like in slice of pizza?

2022-12-12 17:37 UTC, jdroenner commented on datatypes/src/plots/pie_chart.rs
> +    pies: BTreeMap<String, f64>,
maybe "slices"?

2022-12-13 09:00 UTC, ChristianBeilschmidt commented on operators/src/plot/pie_chart.rs
> +pub const MAX_NUMBER_OF_PIES: usize = 32;
[0a40dc3](https://github.com/geo-engine/geoengine/pull/694/commits/0a40dc39413b8c2146aa7e02fb3815c86a28d9ec)

2022-12-13 09:00 UTC, ChristianBeilschmidt commented on datatypes/src/plots/pie_chart.rs
> +    pies: BTreeMap<String, f64>,
[0a40dc3](https://github.com/geo-engine/geoengine/pull/694/commits/0a40dc39413b8c2146aa7e02fb3815c86a28d9ec)

2022-12-13 12:39 UTC, jdroenner approved these changes

2022-12-13 12:40 UTC, jdroenner commented
bors merge

2022-12-13 13:14 UTC, merged