Gbif provider database improvements
geo-engine/geoengine pull request #928
Opened 2024-02-07 10:08 UTC by dbrandenstein

- [ ] I added an entry to [`CHANGELOG.md`](CHANGELOG.md) if knowledge of this change could be valuable to users.

---

Here is a brief summary of what I did:

<TEXT>

2024-02-07 10:08 UTC, dbrandenstein commented
![](https://github.trello.services/images/mini-trello-icon.png) [GBIF Datenbankanfragen Verbesserung](https://trello.com/c/WyocViKI/1594-gbif-datenbankanfragen-verbesserung)

2024-02-12 05:49 UTC, ChristianBeilschmidt requested changes

2024-02-12 08:45 UTC, dbrandenstein commented on services/src/pro/contexts/migrations/migration_0005_gbif_column_selection.rs
> +}
https://github.com/geo-engine/geoengine/pull/928/commits/a08003b68aee871b5b3ef9783e3465b480fcc467

2024-02-12 08:46 UTC, dbrandenstein commented on test_data/gbif/test_data.sql
> +CREATE VIEW occurrences_lite AS (
https://github.com/geo-engine/geoengine/pull/928/commits/5ed887dc1a3a55f219a64ac7188ee15b6fea99dd

2024-02-12 09:07 UTC, ChristianBeilschmidt submitted a review, later dismissed

2024-02-12 14:22 UTC, ChristianBeilschmidt approved these changes

2024-02-12 14:50 UTC, merged